// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe_a8I6PwrP_Lwxc2Y8GgS4ZO5CIevk08',
    appId: '1:581965729031:web:ed2222525292cf5f2309a2',
    messagingSenderId: '581965729031',
    projectId: 'food-ecommerce-9dc53',
    authDomain: 'food-ecommerce-9dc53.firebaseapp.com',
    storageBucket: 'food-ecommerce-9dc53.firebasestorage.app',
    measurementId: 'G-Y9YKNLRY3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-xmQ2ybi1rMYLMu_po-KyYBRhS6L-D2M',
    appId: '1:581965729031:android:8efe2596f562e66b2309a2',
    messagingSenderId: '581965729031',
    projectId: 'food-ecommerce-9dc53',
    storageBucket: 'food-ecommerce-9dc53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyYhcraTmIrSiEVGd7f5MAMPuSYQTCK8I',
    appId: '1:581965729031:ios:b8a5934baa5b058d2309a2',
    messagingSenderId: '581965729031',
    projectId: 'food-ecommerce-9dc53',
    storageBucket: 'food-ecommerce-9dc53.firebasestorage.app',
    iosBundleId: 'com.example.newNin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyYhcraTmIrSiEVGd7f5MAMPuSYQTCK8I',
    appId: '1:581965729031:ios:b8a5934baa5b058d2309a2',
    messagingSenderId: '581965729031',
    projectId: 'food-ecommerce-9dc53',
    storageBucket: 'food-ecommerce-9dc53.firebasestorage.app',
    iosBundleId: 'com.example.newNin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU4aXswtrZWO7dcnOwdZxvf1w0EIOMHsA',
    appId: '1:581965729031:web:38746c6405a342e62309a2',
    messagingSenderId: '581965729031',
    projectId: 'food-ecommerce-9dc53',
    authDomain: 'food-ecommerce-9dc53.firebaseapp.com',
    storageBucket: 'food-ecommerce-9dc53.firebasestorage.app',
    measurementId: 'G-TBLN0T22C5',
  );
}
